config/routes.rb
Rails.application.routes.draw do
  get 'positions/:str' => 'positions#show', str: /[0-9a]{12}[0-2]{3}[0-1]/, as: 'position'
  post 'positions/best'
  get 'about' => 'pages#about'
  get 'search' => 'pages#search'
  post 'search' => 'positions#search'
  
  root :to => 'positions#show', :str => '4260800705130000'

  get '*path', to: 'application#routing_error'
end

app/views/pages/about.html.slim
h1 どうぶつペディア(β)について

h2 データベース構成
div.level1
  p 当サイトはどうぶつしょうぎの全局面を収録したデータベースです。先後反転・左右反転などは同一局面として内部で統合されており、独立な局面としては計<strong class="dark_red">86,848,395</strong>個の局面から構成されます。
  p
    |なお、当サイトでは局面数の削減および局面評価システムの一元化の目的で、本来のどうぶつしょうぎのルールに対して下記の翻訳解釈を適用しています。
    ul
      li 次に「トライ」が可能な局面を合法局面から除外し、相手がトライ可能な状況を作る指し手(＝相手にトライを許す手)を反則手(合法手ではない)と見なします。
      li 本将棋と同様、自玉が相手に取られるような手は反則手と見なします。
      li 上記の仮定に基づいて合法手が一つも存在しない局面を、「詰み」と定義し、それを最終局面とします。(それ以降の局面は非合法局面と見なしデータベースに収録しません)
    |たとえば、#{link_to 'この局面', position_path('0402010000400110')}では、<strong>A3ひよこ打・A1ライオン・B2ゾウ打</strong> までの<strong class="dark_red">3手詰</strong>となります。
  p 正式などうぶつしょうぎでは、王様が取られてしまう局面も立派な合法局面であり、王様を取る手(「キャッチ」)が実際に指されたことをもって終局となります。また、トライに関しても、実際に入玉をした後、相手がその王様を取れないことの確認を持って終局となります。これらはどうぶつしょうぎのコンセプトにおいて極めて重要なポリシーですが、当サイトではデータベース構成および局面評価手法の煩雑化を避けるため、便宜上前述の解釈をさせて頂きました。

h2 当サイト公開の動機
div.level1
  span.dark_red
    |(執筆中)

app/views/pages/search.html.slim
h2 局面検索

table.invisible
  tr
    td.invisible
      div.board
        table
          - for i in 0..3 do
            tr
              - for j in 0..2 do
                td
                  div id=(i.to_s + j.to_s)
    td.invisible style="padding-left:30px;vertical-align:middle;"
      = form_for :search do |f|
        table.search
          - for i in 0..3 do
            tr
              - for j in 0..2 do
                td
                  = f.select id=('cell_' + i.to_s + j.to_s), [["-",0], ["+LI",1], ["-LI",2], ["+KI",3], ["-KI",4], ["+ZO",5], ["-ZO",6], ["+HI",7], ["-HI",8], ["+NI",9], ["-NI",10]]
        p
          strong 先手の持ち駒
          br
          |+KI 
          = f.select :hand_KI, [0,1,2]
          br
          |+ZO 
          = f.select :hand_ZO, [0,1,2]
          br
          |+HI 
          = f.select :hand_HI, [0,1,2]
        p
          strong 手番 
          = f.select :turn, [["先手番",0],["後手番",1]]
        = f.submit "検索"


javascript:
  function updateImage(id, value) {
    $('div#' + id).html('<img src="/assets/hidetchi/' + value + '.png">');
  }
  for (i = 0; i <= 3; i++) { 
    for (j = 0; j <= 2; j++) { 
      updateImage(i.toString() + j.toString(), $('select#search_cell_' + i + j).val());
    }
  }
  $('select').on('change', function (e) {
    var cellID = this.id.split("_")[2];
    updateImage(cellID, this.value);
  });