config/routes.rb
Rails.application.routes.draw do
  get 'positions/:str' => 'positions#show', str: /[0-9a]{12}[0-2]{3}[0-1]/, as: 'position'
  post 'positions/best'
  get 'about' => 'pages#about'
  get 'search' => 'pages#search'
  post 'search' => 'positions#search'
  
  root :to => 'positions#show', :str => '4260800705130000'

  get '*path', to: 'application#routing_error'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><% yield(:title) if content_for?(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="root">
<div id="wrapper">

<div id="side_column">
<center>
<%= link_to image_tag('logo-off.png', :id => 'logo'), '/' %>
<br><span class="dark_red" style='font-weight:bold;font-size:16px'>どうぶつペディア</span>
<br><span class="dark_red">beta</span>
</center>

<ul class="sidemenu">
<li><%= link_to 'サイト説明', about_path %>
<li class="new_section"><%= link_to '初期局面', '/' %>
<li><%= link_to '局面検索', search_path %>
<li class="new_section"><%= link_to 'API(準備中)', '#' %>
<li class="new_section"><%= link_to '局面ペディア(将棋)へ', 'http://kyokumen.jp' %>
</ul>
<% if (notice || alert) %>
<div id="alert_box">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</div>
<% end %>
</div>

<div id="main">

<div id="contents">
<%= yield %>
</div>

</div>

</div>
<div id="footer">
  Hidetchi, All rights reserved
</div>
</body>
</html>